version: "2"

services:
    pluxml_nginx:
        image: nginx:stable-alpine
        ports:
            - 80
        links:
            - pluxml_php
        volumes_from:
            - pluxml_php

    pluxml_php:
        image: goldy/pluxml

        volumes:
            - ./data/:/var/www/pluxml/data/

        # environment:
        #     INSTALL: add this variable to keep install.php
volumes:
  data: {}
